import type { SchemaDescriptor } from '../types'

// The Biosafety Clearing-House identity of the `biosafetyDecision` record type.
const dec: SchemaDescriptor = {
  schema: 'biosafetyDecision',
  name: "Decision",
  description: "A Decision record in the Biosafety Clearing-House.",
  fields: {
  "government": { title: "Country submitting the decision or communication", type: 'term', mandatory: true, example: {"identifier":"af"} },
  "authorities": { title: "Competent National Authority(ies) responsible for the decision or communication", type: 'reference[]', mandatory: true, example: [{"identifier":"78AFAA88-47EA-9333-AD6E-C21BCB17DE21@1"}] },
  "title": { title: "Title / Reference number of the decision or communication", type: 'lstring', mandatory: true, example: {"en":"Test title"} },
  "date": { title: "Date of the decision", type: 'datetime', mandatory: true },
  "takenPriorEntryIntoForce": { title: "Is the decision taken prior to entry into force of the Protocol?", type: 'bool', example: true },
  "jurisdictions": { title: "", type: 'term[]' },
  "jurisdictionsDetails": { title: "Jurisdiction", type: 'lstring', example: {"en":"Test Jurisdiction"} },
  "isAmendment": { title: "Is this an amendment to a decision or communication already published on the BCH?", type: 'bool', mandatory: true },
  "amendedRecords": { title: "Please select the record(s) containing the decision or communication being amended", type: 'reference[]', example: [{"identifier":"E2795D50-46AB-E234-96D0-D1164C382C7D@1"}] },
  "amendmentsDetails": { title: "Please provide a brief summary of the amendment(s)", type: 'lstring', example: {"en":"<div><!--block-->Test Summary</div>"} },
  "decisionTypes": { title: "Subject of the decision, notification, communication or declaration", type: 'term[]', mandatory: true, example: [{"identifier":"8979219B-330B-424F-A52C-209D4B4B65C0"}] },
  "exporters": { title: "Please provide Exporter’s contact details", type: 'reference[]', example: [{"identifier":"3CBDA8AA-4A16-CA5C-D405-7F4E865A60AA@1"}] },
  "importers": { title: "Please provide Importer’s contact details", type: 'reference[]' },
  "receiptDate": { title: "Date on which the notification was received", type: 'datetime', example: [{"identifier":"3CBDA8AA-4A16-CA5C-D405-7F4E865A60AA@1"}] },
  "receiptAcknowledgementDate": { title: "Date on which acknowledgement of receipt of the notification was sent to the notifier", type: 'datetime' },
  "communicationDate": { title: "Date on which the decision was communicated to the notifier", type: 'datetime' },
  "addressesTransboundaryMovement": { title: "Was the decision triggered by a request for a transboundary movement of LMOs into your country?", type: 'bool', example: true },
  "appliesToTransboundaryMovement": { title: "Does the decision apply to transboundary movements of LMO(s) into your country?", type: 'bool', example: true },
  "involvesFieldTrial": { title: "Does the decision involve field trials?", type: 'bool', example: true },
  "involvesCommercialRelease": { title: "Does the decision allow commercial release?", type: 'bool', example: true },
  "appliesToSubsequentIntroductions": { title: "Will the decision apply to subsequent introductions of the same LMO(s) into the environment?", type: 'bool', example: true },
  "uses": { title: "Use(s) of LMO", type: 'term[]', example: [{"identifier":"91BEAF12-ABE1-4294-AD3B-507935894C78"}] },
  "takenInAccordanceWithA116": { title: "Has the decision been taken in the absence of a domestic regulatory framework and in accordance with Article 11.6?", type: 'bool', example: true },
  "decisionResult": { title: "Result of the decision", type: 'term', example: {"identifier":"3B9ECE67-B35C-40FF-8C06-4EA5FF762899"} },
  "conditions": { title: "Specify the conditions", type: 'lstring', example: {"en":"Test information"} },
  "reasons": { title: "Provide reasons", type: 'lstring', example: {"en":"Test information"} },
  "extensionPeriod": { title: "Specify the time extension in days", type: 'int', example: 1 },
  "movementAllowedUnderA131A": { title: "Subject of the decision under the simplified procedure", type: 'bool', example: true },
  "exemptFromAIA": { title: "Decision specifying that the import of the LMO is exempt from the Advance Informed Agreement (AIA) procedure", type: 'bool', example: true },
  "appliesToSubsequentImports": { title: "Does the decision apply to subsequent similar imports of LMOs?", type: 'bool', example: true },
  "transboundaryMovementType": { title: "Type of transboundary movement", type: 'term', example: {"identifier":"22B915C4-193E-4087-89ED-D104EEEC4330"} },
  "releaseInformation": { title: "Information on the place where the occurrence and/or release occurred", type: 'lstring', example: {"en":"Test information"} },
  "estimatedQuantities": { title: "Available relevant information on the estimated quantities and relevant characteristics and/or traits of the living modified organism", type: 'lstring', example: {"en":"Test information"} },
  "releaseCircumstance": { title: "Information on the circumstances of the release", type: 'lstring', example: {"en":"Test information"} },
  "releaseDate": { title: "Information on the estimated date of the release", type: 'datetime' },
  "lmoUseInformation": { title: "Information on the use of the living modified organism in the originating Party", type: 'lstring', example: {"en":"Test information"} },
  "adverseEffectInformation": { title: "Information about the possible adverse effects on the conservation and sustainable use of biological diversity, taking also into account risks to human health, as well as available information about possible risk management measures", type: 'lstring', example: {"en":"Test information"} },
  "pointOfContact": { title: "A point of contact for further information", type: 'reference[]', example: [{"identifier":"3CBDA8AA-4A16-CA5C-D405-7F4E865A60AA@1"}] },
  "otherTransboundryInformation": { title: "Any other relevant information", type: 'lstring', example: {"en":"Test information"} },
  "otherTransboundryInformation": { title: "Any other relevant information", type: 'lstring', example: {"en":"Test information"} },
  "isForCommercialUse": { title: "Is this decision related to an LMO for commercial use?", type: 'bool', example: true },
  "forwardToOECD": { title: "Should this decision be forwarded to the OECD Secretariat for possible inclusion in the BioTrack Product Database?", type: 'bool', example: true },
  "isForFoodSafety": { title: "Is this decision related to food safety?", type: 'bool', example: true },
  "codexConducted": { title: "Was it conducted in accordance with the Codex Alimentarius Guideline for the Conduct of Food Safety Assessment of Foods Derived from Recombinant-DNA Plants?", type: 'bool', example: true },
  "forwardToFAO": { title: "Should this information be forwarded to the Secretariat of the FAO GM Foods Platform?", type: 'bool', example: true },
  "modifiedOrganisms": { title: "LMO identification", type: 'reference[]', example: [{"identifier":"1E027990-5D44-F3AF-75E3-715B60BFD3CD@8"}] },
  "riskAssessments": { title: "Risk assessment", type: 'reference[]', example: [{"identifier":"486389BF-3C48-F2C9-2622-AC3D8E119845@4"}] },
  "documents": { title: "Document text", type: 'link[]', example: [{"url":"https://www.google.com","name":"Google","language":"en"}] },
  "expires": { title: "Should this information be confirmed or updated after two years from the date of submission?", type: 'bool', mandatory: true, example: true },
  "relevantInformation": { title: "Any other relevant information", type: 'lstring', example: {"en":"<div><!--block-->Test Information</div>"} },
  "relevantDocuments": { title: "Any other relevant documents", type: 'link[]', example: [{"url":"https://www.google.com","name":"Google","language":"en"}] }
  }
}

export default dec
