version: 2

_defaults: &defaults
  docker:
    - image: docker:24.0.5
  working_directory: ~/scbd/clearing-house-documentation
  parallelism: 1

_run:
  buildDocker: &buildDocker
    name: Build docker image
    command: |
      docker info
      docker build -t output --build-arg COMMIT=$CIRCLE_SHA1 --build-arg VERSION=$CIRCLE_SHA1 --build-arg BRANCH=${CIRCLE_BRANCH:-master} --build-arg TAG=$CIRCLE_TAG .
  testImage: &testImage
    name: Test docker image
    command: |
      docker run --name clearing-house-documentation -e "VITE_CLEARING_HOUSE=abs" -d -p 8000:8000 output
      sleep 30
      docker ps
      docker logs clearing-house-documentation
      docker exec clearing-house-documentation curl --retry 10 --retry-delay 5 -v http://localhost:8000/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.7
      - run: *buildDocker
      - run: *testImage

  build-deploy-branches:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.7
      - run: *buildDocker
      - run: *testImage
      - deploy:
          name: Deploy build to docker hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag output scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            docker push scbd/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH

  build_and_deploy_releases:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.7
      - run: *buildDocker
      - run: *testImage
      - deploy:
          name: Deploy release build to docker hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag output scbd/$CIRCLE_PROJECT_REPONAME:release-${CIRCLE_BRANCH//release\//}
            docker push scbd/$CIRCLE_PROJECT_REPONAME:release-${CIRCLE_BRANCH//release\//}

  build_and_deploy_tags:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.7
      - run: *buildDocker
      - run: *testImage
      - deploy:
          name: Deploy tag build to docker hub
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" == 'scbd' ]; then
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              docker tag output scbd/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG//v/}
              docker tag output scbd/$CIRCLE_PROJECT_REPONAME:latest
              docker push scbd/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG//v/}
              docker push scbd/$CIRCLE_PROJECT_REPONAME:latest
            else
              echo "Invalid tag, only scbd tags allowed"
            fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^(master|dev|stg)$/
                - /^release\/.*/
            tags:
              ignore:
                - /^v?[0-9]+(\.[0-9]+)*$/

      - build-deploy-branches:
          filters:
            branches:
              only: /^(master|dev|stg)$/
      - build_and_deploy_releases:
          filters:
            branches:
              only:
                - /^release\/.*/
      - build_and_deploy_tags:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*$/
