<template>
  <div>
    <!-- Table to display filtered data -->
    <table>
      <thead>
        <tr>
          <th><strong>Record Type</strong></th>
          <th><strong>Schema</strong></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in filteredRecords" :key="item.recordType">
          <td>{{ item.recordType }}</td>
          <td>
            <a :href="item.schemaUrl">{{ item.schemaName }}</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from "vue";

const selectedFilter = ref("");
const absRecordTypes = [
  {
    recordType: "CNA",
    schemaUrl: "/abs/cna/schema",
    schemaName: "Competent National Authority",
  },
  {
    recordType: "Contact",
    schemaUrl: "/abs/contact/schema",
    schemaName: "Contact",
  },
  { recordType: "CP", schemaUrl: "/abs/cp/schema", schemaName: "Checkpoint" },
  {
    recordType: "CPC",
    schemaUrl: "/abs/cpc/schema",
    schemaName: "Checkpoint Communiqué",
  },
  {
    recordType: "IRCC",
    schemaUrl: "/abs/ircc/schema",
    schemaName: "Internationally Recognized Certificates of Compliance",
  },
  {
    recordType: "MSR",
    schemaUrl: "/abs/msr/schema",
    schemaName: "Legislative, Administrative or Policy Measures",
  },
  {
    recordType: "NFP",
    schemaUrl: "/abs/nfp/schema",
    schemaName: "National Focal Point",
  },
  {
    recordType: "VLR",
    schemaUrl: "/abs/vlr/schema",
    schemaName: "Virtual Library Resources",
  },
  {
    recordType: "PRO",
    schemaUrl: "/abs/pro/schema",
    schemaName: "ABS Procedures",
  },
];

const bchRecordTypes = [
  {
    recordType: "CNA",
    schemaUrl: "/bch/cna/schema",
    schemaName: "Competent National Authority",
  },
  {
    recordType: "DEC",
    schemaUrl: "/bch/dec/schema",
    schemaName: "Country's Decision or any other Communication",
  },
  {
    recordType: "GENE",
    schemaUrl: "/bch/gene/schema",
    schemaName: "Genetic elements",
  },
  {
    recordType: "IRA",
    schemaUrl: "/bch/ira/schema",
    schemaName:
      "Risk Assessments generated by an independent or non-regulatory process",
  },
  {
    recordType: "LAW",
    schemaUrl: "/bch/law/schema",
    schemaName: "Biosafety Law, Regulation, Guidelines and Agreements",
  },
  {
    recordType: "LMO",
    schemaUrl: "/bch/lmo/schema",
    schemaName: "Living Modified Organism",
  },
  {
    recordType: "NFP",
    schemaUrl: "/bch/nfp/schema",
    schemaName: "National Focal Point",
  },
  {
    recordType: "ORG",
    schemaUrl: "/bch/org/schema",
    schemaName: "Organization",
  },
  {
    recordType: "VLR",
    schemaUrl: "/bch/vlr/schema",
    schemaName: "Virtual Library Resources",
  },
];

const chmRecordTypes = [
  {
    recordType: "VLR",
    schemaUrl: "/chm/vlr/schema",
    schemaName: "Virtual Library Resources",
  },
];

onMounted(() => {
  selectedFilter.value = window.location.pathname.split("/")[1];
});

const filteredRecords = computed(() => {
  const recordTypesMap = {
    abs: absRecordTypes,
    bch: bchRecordTypes,
    chm: chmRecordTypes,
  };
  
  return recordTypesMap[selectedFilter.value] || [];
});
</script>
