import type { SchemaDescriptor } from '../types'

// The Online Reporting Tool identity of the `nationalReport7BinaryIndicatorData` record type.
const nationalReportBinaryIndicatorData: SchemaDescriptor = {
  schema: 'nationalReport7BinaryIndicatorData',
  name: "National Report Binary Indicator Data",
  description: "A National Report Binary Indicator Data record in the Online Reporting Tool.",
  fields: {
  "government": { title: "Government", titleLink: '/thesaurus/countries', type: 'term', mandatory: true, example: {"identifier":"af"} },
  "binaryResponseGoalC": { title: "BIN.B Number of countries with national constitution or legislation recognizing and implementing and monitoring a right to a healthy environment", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-C-13"},"responses":{"13_1":"??","13_2":"??","13_3":"yesFully","13_3_alt":"??"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseGoalB": { title: "BIN.C.13 Number of countries that have operational legislative, administrative or policy frameworks which relate to Target 13", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-B"},"responses":{"b_1":"yesFully","b_2":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget1": { title: "BIN.1 Number of countries using terrestrial and marine spatial planning to identify areas of high biodiversity importance in national development planning", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-1"},"responses":{"1_a":"yesFully","1_b":"yesFully","1_c":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget6": { title: "BIN.6 Number of countries adopting relevant national legislation and adequately resourcing the prevention or control of invasive alien species", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-6"},"responses":{"6_1":"yesFully","6_2":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget8": { title: "BIN.8 Number of countries with nationally determined contributions, long-term strategies, national adaptation plans and adaptation communications that reflect biodiversity", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-8"},"responses":{"8_1":"??","8_2":"yesFully","8_3":"??","8_4":"??"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget9": { title: "BIN.9 Number of countries with legal instruments to regulate the use and trade of wild species, and respecting customary sustainable use by indigenous peoples and local communities", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-9"},"responses":{"9_1":"yesFully","9_2":"??","9_3":"??","9_4":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget12": { title: "BIN.12 Number of countries with urban sustainability plans referring to green and/or blue spatial management", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-12"},"responses":{"12_1":"??","12_2":"??"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget15": { title: "BIN.15 Number of countries taking legal, administrative or policy measures to ensure that Target 15 is achieved", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-15"},"responses":{"15_1":"yesFully","15_2":"yesFully","15_3":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget16": { title: "BIN.16 Number of countries developing, adopting or implementing policy instruments aimed at supporting the shift to sustainable consumption and production (SDG Indicator 12.1.1)", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-16"},"responses":{"16_1":"yesFully","16_2":"yesFully","16_3":"??"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget17": { title: "BIN.17 Number of countries with capacity and measures in place related to Target 17", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-17"},"responses":{"17_1":"yesFully","17_2":"yesFully","17_3":"??","17_4":"yesFully","17_5":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget20": { title: "", type: 'object' },
  "binaryResponseTarget22": { title: "BIN.22 Number of countries recognizing the legal rights of indigenous peoples and local communities, environmental human rights defenders, women, youth and persons with disabilities with respect to their traditional territories, cultures and practices", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-22"},"responses":{"22_1_a":["indigenousPeoplesLocalCommunities"],"22_1_b":["cultureAndPractices"],"22_1_c":"yes","22_1_d":["indigenousPeoplesLocalCommunities"],"22_1_e":["indigenousPeoplesLocalCommunities"],"22_2":"yesFully","22_3":"??","22_4":"yes","22_5_a":["indigenousPeoplesLocalCommunities"],"22_5_b":["cultureAndPractices"],"22_5_c":"yes"},"comments":{"en":"<p>Test Info</p>"}} },
  "binaryResponseTarget23": { title: "BIN.23 Number of countries where the legal framework (including customary law) guarantees women's equal rights to land ownership and/or control", type: 'object', example: {"indicator":{"identifier":"KMGBF-INDICATOR-BIN-23"},"responses":{"23_1":"yesFully","23_2":"yesFully","23_3":"yesFully","23_4":"??","23_5":"yes","23_6":"yesFully","23_7":"yesFully"},"comments":{"en":"<p>Test Info</p>"}} }
  }
}

export default nationalReportBinaryIndicatorData
